del  .\Blog.Core.Api\bin\*.*   /s /q
del  .\Blog.Core.Api\obj\*.*   /s /q
del  .\Blog.Core.Api\wwwroot\ui\*.*   /s /q
del  .\Blog.Core.Api\WMBlog.db   /s /q
del  .\Blog.Core.Common\bin\*.*   /s /q
del  .\Blog.Core.Common\obj\*.*   /s /q
del  .\Blog.Core.EventBus\bin\*.*   /s /q
del  .\Blog.Core.EventBus\obj\*.*   /s /q
del  .\Blog.Core.Extensions\bin\*.*   /s /q
del  .\Blog.Core.FrameWork\bin\*.*   /s /q
del  .\Blog.Core.Gateway\bin\*.*   /s /q
del  .\Blog.Core.IServices\bin\*.*   /s /q
del  .\Blog.Core.Model\bin\*.*   /s /q
del  .\Blog.Core.Repository\bin\*.*   /s /q
del  .\Blog.Core.Serilog.Es\bin\*.*   /s /q
del  .\Blog.Core.Services\bin\*.*   /s /q
del  .\Blog.Core.Tasks\bin\*.*   /s /q
del  .\Blog.Core.Tests\bin\*.*   /s /q
del  .\Ocelot.Provider.Nacos\bin\*.*   /s /q

del  .\Blog.Core.Extensions\obj\*.*   /s /q
del  .\Blog.Core.FrameWork\obj\*.*   /s /q
del  .\Blog.Core.Gateway\obj\*.*   /s /q
del  .\Blog.Core.IServices\obj\*.*   /s /q
del  .\Blog.Core.Model\obj\*.*   /s /q
del  .\Blog.Core.Repository\obj\*.*   /s /q
del  .\Blog.Core.Serilog.Es\obj\*.*   /s /q
del  .\Blog.Core.Services\obj\*.*   /s /q
del  .\Blog.Core.Tasks\obj\*.*   /s /q
del  .\Blog.Core.Tests\obj\*.*   /s /q
del  .\Ocelot.Provider.Nacos\obj\*.*   /s /q